# This workflow is for use locally using [act](https://github.com/nektos/act).

on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  run-local:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        # with:
        #   path: "rewritable-pr-comment"
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        name: Set up Node.js
        with:
          node-version: 16

      # Build
      # Build
      - name: "Install dependencies and build"
        run: |
          sudo apt-get install -y curl jq
          npm install -g semver

      - name: test action locally
        uses: ./
        with:
          DRY_RUN: "false"
          TAG_CONTEXT: "branch"
          PRERELEASE: "true"
          PRERELEASE_SUFFIX: "bats"
          VERBOSE: "true"
