name: "Create or update issues from TODOs found in code"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *" # 15:00 UTC daily = 01:00 AEST daily

permissions:
  issues: write
  pull-requests: write
  contents: read

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  todo-issues:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: "actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c" # v3
      - name: "Check for TODOs and create or update issues"
        uses: "alstr/todo-to-issue-action@b50288792858dfc84690dbd7c1ecf99a4a1b52b8" # v4
        id: "todo"
