name: "Lint Markdown Files"

# https://github.com/reviewdog/action-markdownlint

on:
  pull_request:
    paths:
      - "**/*.md"
    branches:
      - main
      - master
      - "!repo-sync/**"
      - "!renovate/**"
      - "!update/pre-commit-hooks/**"
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: markdownlint
        uses: reviewdog/action-markdownlint@97e3df02fe1573d505a7b268046a44fa5409cbc3 # tag=v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          filter_mode: added
          fail_on_error: false
          ### Flags for markdownlint-cli ###
          # markdownlint_flags: .
