name: "Lint Docker"

on:
  pull_request:
    branches:
      - main
      - master
      - "!repo-sync/**"
      - "!renovate/**"
      - "!update/pre-commit-hooks/**"
  workflow_dispatch:

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hadolint:
    name: "Lint Docker with hadolint"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: run tflint
        uses: reviewdog/action-hadolint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: "false"
          level: warning
          filter_mode: "nofilter" # Optional. Check all files, not just the diff
          # tflint_version: "v0.24.0" # Optional. Custom version, instead of latest
          # tflint_rulesets: "azurerm google" # Optional. Extra official rulesets to install
          # flags: "--module" # Optional. Add custom tflint flags
